apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth0-mgmt-api
  description: Auth0 Management API service for managing applications and authentication
  annotations:
    github.com/project-slug: harshsingh11234/auth0-mgmt-api
    backstage.io/techdocs-ref: dir:.
  tags:
    - auth0
    - authentication
    - management-api
    - nodejs
    - api
  links:
    - url: http://localhost:3000
      title: Local Development API
      icon: web
    - url: https://github.com/harshsingh11234/auth0-mgmt-api/
      title: GitHub Repository
      icon: github
spec:
  type: service
  lifecycle: production
  owner: user:default/guest  # ✅ Use default guest user
  # system: authentication    # ❌ Remove this line
  providesApis:
    - auth0-management
  # dependsOn:                # ❌ Remove dependencies
  #   - resource:default/auth0-tenant

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth0-management
  description: REST API for Auth0 management operations
spec:
  type: openapi
  lifecycle: production
  owner: user:default/guest  # ✅ Use default guest user
  # system: authentication    # ❌ Remove this line
  definition: |
    openapi: 3.0.0
    info:
      title: Auth0 Management API
      version: 1.0.0
    paths:
      /api/auth0/token:
        get:
          summary: Get Bearer Token
          responses:
            '200':
              description: Successful response
      /api/auth0/applications:
        get:
          summary: List all applications
          responses:
            '200':
              description: Successful response
