apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth0-management-api
  description: Auth0 Management API service for managing applications and authentication
  annotations:
    github.com/project-slug: myorg/auth0-management-api  # ✅ Update with actual org/repo
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/harshsingh11234/auth0-mgmt-api/  # ✅ Add this
  tags:
    - auth0
    - authentication
    - management-api
    - nodejs
    - api
  links:
    - url: https://dev-a0e8fgdagji16lue.us.auth0.com/api/v2/ # ✅ Update with actual URL
      title: Production API
      icon: web
    - url: https://auth0.com/docs/api/management/v2
      title: Auth0 Management API Docs
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: authentication
  providesApis:
    - auth0-management
  dependsOn:
    - resource:default/auth0-tenant  # ✅ Better to specify namespace

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth0-management
  description: REST API for Auth0 management operations
  annotations:
    backstage.io/definition-at-location: url:https://github.com/myorg/auth0-management-api/blob/main/openapi.yaml  # ✅ Optional: link to actual OpenAPI spec
spec:
  type: openapi
  lifecycle: production
  owner: platform-team
  system: authentication
  definition: |
    openapi: 3.0.0
    info:
      title: Auth0 Management API
      version: 1.0.0
      description: API for managing Auth0 applications and authentication
    servers:  # ✅ Add servers
      - url: https://dev-a0e8fgdagji16lue.us.auth0.com/api/v2/
        description: Production server
    paths:
      /api/auth0/token:
        get:
          summary: Get Bearer Token
          description: Retrieves a bearer token for Auth0 API authentication
          responses:
            '200':
              description: Successful response
              content:  # ✅ Add response schema
                application/json:
                  schema:
                    type: object
                    properties:
                      access_token:
                        type: string
                      token_type:
                        type: string
      /api/auth0/applications:
        get:
          summary: List all applications
          responses:
            '200':
              description: Successful response
        post:
          summary: Create new application
          requestBody:  # ✅ Add request body
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
          responses:
            '201':
              description: Application created
      /api/auth0/applications/{clientId}:
        get:
          summary: Get application by ID
          parameters:
            - name: clientId
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Successful response
        patch:
          summary: Update application
          parameters:
            - name: clientId
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Application updated
        delete:
          summary: Delete application
          parameters:
            - name: clientId
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Application deleted

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: auth0-tenant
  description: Auth0 Tenant Configuration
  annotations:
    auth0.com/tenant-name: dev-a0e8fgdagji16lue  # ✅ Add tenant info
spec:
  type: auth0-instance
  lifecycle: production
  owner: platform-team
  system: authentication

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: authentication
  description: Authentication and Authorization System
spec:
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Engineering Team
spec:
  type: team
  children: []